export const w = 1200,
  h = 600,
  r = 15,
  highlightBuffer = 5,
  pixelsPerMeter = 100,
  metersPerPixel = 1 / pixelsPerMeter,
  timeStep = 1 / 60,
  velocityIterations = 4,
  positionIterations = 2,
  angleLim = 0.35 * Math.PI,
  friction = 0.95,
  restitution = 0,
  maxTorque = 6,
  // speedMag = 10,
  speedMag = 1,
  nnInfo = { widths: [16, 8], activation: "elu" }
// nCreatures = 24
// nBatches = 2
// epLength = 3000,
// mutationMag = 1,
// selectionRatio = 0.25
